// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE3uEzMTGFromvN6k12llsrt4eJB6X4UU',
    appId: '1:142759646530:web:b0c802bb5529ea33b364db',
    messagingSenderId: '142759646530',
    projectId: 'globalchat-a4ae7',
    authDomain: 'globalchat-a4ae7.firebaseapp.com',
    storageBucket: 'globalchat-a4ae7.firebasestorage.app',
    measurementId: 'G-4T6Q860817',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbSV2EFx1-qdOX9IOvhc-uGb8JqJyGSB4',
    appId: '1:142759646530:android:04508786ddb906c9b364db',
    messagingSenderId: '142759646530',
    projectId: 'globalchat-a4ae7',
    storageBucket: 'globalchat-a4ae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIB0INxpT5bf-Vcq9mV4gJwQpjna7Lpw',
    appId: '1:142759646530:ios:9b3b35df0f0d7d6db364db',
    messagingSenderId: '142759646530',
    projectId: 'globalchat-a4ae7',
    storageBucket: 'globalchat-a4ae7.firebasestorage.app',
    iosBundleId: 'com.example.globalchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE3uEzMTGFromvN6k12llsrt4eJB6X4UU',
    appId: '1:142759646530:web:7381d213aea9859db364db',
    messagingSenderId: '142759646530',
    projectId: 'globalchat-a4ae7',
    authDomain: 'globalchat-a4ae7.firebaseapp.com',
    storageBucket: 'globalchat-a4ae7.firebasestorage.app',
    measurementId: 'G-DTLZ6TLLRL',
  );
}
